logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8081
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coderscircle
    username: YOUR_DATABASE_NAME
    password: YOUR_DATABASE_PASSWORD

  mail:
    host: smtp.qq.com
    port: 587
    username: YOUR_EMAIL_NAME
    password: YOUR_EMAIL_PASSWORD
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  data:
    redis:
      host: localhost
      port: 6379

mybatis-plus:
  type-aliases-package: com.kz.coderscircle.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret-key: "YOUR-JWT-KEY"
  # JWT的过期时间，单位为秒 (86400 = 24小时)
  expire-time: 86400

# 文件存储相关配置
file-storage:
  path: "E:/IDEA/JavaWSpace/coders-circle/coders-circle-files/"